### PR TITLE
Improve performance by improving the handling of hashes

### PR DESCRIPTION
**Pull request by dferreyra**
Performance is improved in the following ways:
  1. Eliminate Hash.ComputeHash() that returns a string, and
     Hash.Sum() that converts the string to an array of hash bytes
  2. Avoid the use of Enumerable.Skip() and Enumerable.Take()
  3. Avoid the use of Array.Reverse() on little-endian architectures

Change library to use HashAlgorithm directly.  Remove Hash.cs, Hash128.cs
and their corresponding tests.

Add Utils.HashBytesToUInt32() and Utils.HashBytesToUInt64() functions
that convert a set of .NET hash bytes into a uint or ulong regardless
of the endianness of the architecture.

Fix Utils.HashKernel128() to conform to how HashKernel() works,
and fix corresponding unit tests.

Add TestProbabilisticDataStructures.TestHashKernelFNV1()
that confirms that the HashKernel() function returns
the same values as the HashKernel() function in
https://github.com/tylertreat/BoomFilters running in Go.

Move the original Hash.ComputeHash() that returns a string
to Utils.ComputeHashAsString().  This function is no longer
used by the library, but the unit tests that use it remain.

### CODE REVIEW

**Comment by dferreyra** [comment]
Here's another unsolicited change I'd like to propose.  I'd only intended to make the speed improvements I'd done for BloomFilter64 and apply them to the rest of the library, but while doing that, I noticed that the way I'd handled the hashes in BloomFilter64 and Hash128 were off relative to what the rest of the library did.  Getting that right while improving performance led me to the changes I've proposed here.  I didn't intend for them to be so disruptive.

In any case, this change preserves how hash values are utilized.  Specifically, the way various integer values are extracted from the hash values matches what was there before and continues to match what the Go "BoomFilters" library does.  I added TestHashKernelFNV1 to confirm that this approach literally matches what is done in the "BoomFilters" library.

On my computer, these changes improve the speed of BloomFilter by 135%.  When I run the profiler, the MD5 hash calculation itself is now what dominates.

**Comment by dferreyra** [comment]
I wanted to make a comment about the logic of keeping both BloomFilter and BloomFilter64 as separate classes.  Maybe this is obvious, but I wanted to make my thinking explicit.

In my rough tests (with this commit), BloomFilter is 35% faster than BloomFilter64.  That performance hit to support large Bloom filters is probably reason enough to keep them separate.

In addition, BloomFilter64 requires 128 bits of hash material vs. only 64 bits for BloomFilter.  If, in my tests, I replace the MD5 hash with the FNV1 64-bit hash (the hash used in the Go "BoomFilter" library) for BloomFilter and the FNV1 128-bit hash for BloomFilter64, BloomFilter becomes 220% faster than BloomFilter64.  That would be an even greater performance hit for folks that don't need large Bloom filters.

**Comment by dferreyra** [comment]
Thanks for the great library!

**Comment by mattlorimor** [comment]
Thanks, @dferreyra. I'll try to get this looked at tomorrow evening.

**Pull request merged**
